README.md
Just fixing wrong link in Screenshots section. 
- Formatted README wen saved the file.
=> fixed wrong link in README

lua/feline/init.lua
=> Revert "fix for issue#23, feline makes splash screen disappear"

lua/feline/init.lua
=> Fix qf default statusline

README.md, lua/feline/providers/file.lua
=> feat(file_info): add read-only indicator

README.md, lua/feline/generator.lua, lua/feline/init.lua, lua/feline/presets/default.lua, lua/feline/presets/noicon.lua
Closes #49 
Currently added support for new format and made presets use the new format. ~~Need to add a deprecation warning for people using the old format and change docs accordingly before merging this.~~ It's ready for merge! New format works fine for me. Though I'd appreciate if others were willing to give it a spin, tell me if it works fine and report any problems encountered.
=> New format for components

lua/feline/providers/git.lua
https://github.com/lewis6991/gitsigns.nvim/blob/f2437cd95a9320c1021edd5fc5ac2e1f9e47fef3/doc/gitsigns.txt#L711
=> providers/git: Show branch name even if no files are opened

README.md, lua/feline/defaults.lua, lua/feline/generator.lua, lua/feline/init.lua, lua/feline/providers/cursor.lua, lua/feline/providers/file.lua, lua/feline/providers/git.lua, lua/feline/providers/lsp.lua
Closes #52
I'd like people to review it and check if everything works as intended before I merge this.
=> fix: make statusline update in all windows

lua/feline/init.lua
Attempt to fix #63. Can you test this @famiu?
=> fix: don't defer current window reset

README.md
Self explanatory, in response to [your request on reddit](https://www.reddit.com/r/neovim/comments/ppfgq3/felinenvim_version_01_released/hd5rjbe/?context=3)
=> Added my feline config + screenshot

README.md, lua/feline/generator.lua
Closes #84 
Since this adds a lot to the table, I think it needs to be tested well before merging, but from the testing I've done, it seems to work fine
=> feat: allow all component values to take winid

README.md, lua/feline/defaults.lua, lua/feline/generator.lua
Closes #91 
It's a nice feature to have but I'm slightly worried about the performance implications of this. Not to mention this is also a breaking change
=> feat: make `force_inactive` and `disable` use Lua patterns

lua/feline/providers/vi_mode.lua
=> feat(vi_mode): Add nt mode

USAGE.md, doc/feline.txt, lua/feline/providers/file.lua, lua/feline/providers/init.lua
Just a small addition to show `fileformat` (`unix`, `dos`, or `mac`) in status line.
=> feat: add fileformat provider

lua/feline/providers/lsp.lua
=> fix: fix LSP provider

.github/workflows/pr_check.yml, CONTRIBUTING.md, benchmark/startup.lua, benchmark/statusline.lua, lua/feline/defaults.lua, lua/feline/generator.lua, lua/feline/init.lua, lua/feline/presets/default.lua, lua/feline/presets/init.lua, lua/feline/presets/noicon.lua, lua/feline/providers/cursor.lua, lua/feline/providers/file.lua, lua/feline/providers/git.lua, lua/feline/providers/init.lua, lua/feline/providers/lsp.lua, lua/feline/providers/vi_mode.lua, lua/feline/themes/default.lua, lua/feline/themes/init.lua, minimal_init.lua, stylua.toml
Only formatted everything with stylua. No changes to the code.
And also adds a github workflow to check style for PRs.
=> style: format with stylua

lua/feline/providers/file.lua
=> fix(providers/file_info): Remove unnecessary trailing space

USAGE.md, lua/feline/defaults.lua, lua/feline/generator.lua, lua/feline/init.lua
Adds a `conditional_components` key to the setup function, which allows conditionally using a components table.
Closes #141
=> feat: add support for conditional components

lua/feline/providers/vi_mode.lua
=> fix: remove duplicate `mode_alias` index

lua/feline/providers/file.lua
Reverts feline-nvim/feline.nvim#251
=> fix: correctly get file extensions

USAGE.md, lua/feline/providers/cursor.lua
=> feat: add `reverse` option to scroll bar provider

USAGE.md, lua/feline/providers/cursor.lua
Allows using custom padding and a custom format for the `position`
provider.
=> feat: add more configuration options for `position` provider

README.md
I really enjoyed playing with feline (amazing name btw ^^)
So I wanted to share what I ended up with. Who knows, it might help someone one day !
Here is my [config](https://gist.github.com/Toufyx/d6b48a0a12ceff02268be49db0a97ddf)
and here is my (slightly photoshoped) [screenshot](https://user-images.githubusercontent.com/10991276/187600545-034cf707-08c9-456e-af3e-6d4baf1580a9.png) 
Feel free to merge it if you think it is worth it 😄
=> docs: add toufyx example configuration

README.md
I created a plugin which provides a feline configuration based on one_monokai colorscheme. I just added that link and screenshot to README.md
=> Added my feline config to README.md

USAGE.md, lua/feline/providers/cursor.lua, lua/feline/providers/init.lua
Now that [cmd_height](https://github.com/neovim/neovim/pull/16251) can be set to zero, i think this is a nice addition to feline
idk how to categorize this tho
=> feat: Added provider search_count

lua/feline/providers/cursor.lua
=> fix(providers): search_count deal with empty/incomplete results

README.md
=> added dharmx's config
