README.md
lua/feline/providers/file.lua
lua/feline/providers/init.lua

Encoding of a file is common information. So I added it. Use
```
provider = 'file_encoding'
```

Add file_encoding support

---

lua/feline/providers/lsp.lua

The result of `vim.lsp.buf_get_clients()` should not be iterated by `ipairs`. See its [source](https://github.com/neovim/neovim/blob/26bd5a58dff1b920757f3bc010c2e8f9dbfc9d40/runtime/lua/vim/lsp.lua#L1432) in neovim/neovim.
This line
```lua
result[client_id] = client
```
If a user opens multiple buffers, `client_id` may not start from 1. If you iterate with `ipairs`, you will get an "empty table".
Change to `pairs` would fix it.

Fix lsp provider

---

lua/feline/init.lua

Allows `feline` to run properly without any configuration when `nvim-web-devicons` is not installed
- defaults to the `noicon` when `nvim-web-devicons` is not present
- default stays at `default` when `nvim-web-devicons` is present
---
Based on discussions in #17

feat: default to `noicon` without "devicons"

---

README.md

I've changed my config. In this commit, I changed my config link to make the screenshot and config link match.

Fix 6cdh's config link

---

README.md
lua/feline/generator.lua

If a components hl option is a string, or a function that returns
a string, accept it as an existing or externally defined hlgroup
and don't generate our own.
See #21

feat: Use hl as hlgroup if hl is a string or fn->string

---

lua/feline/init.lua

This closes [issue #23](https://github.com/famiu/feline.nvim/issues/23).
[This comment in Powerline issue #250](https://github.com/powerline/powerline/issues/250#issuecomment-52275269) gave me the lead with:
```vim
" Hack to show startup screen. Problems in GUI:
" - Defining local value of &statusline option while computing global value 
"   purges startup screen.
" - Defining highlight group while computing statusline purges startup 
"   screen.
" This hack removes the “while computing statusline” part: both things are 
" defined, but they are defined right now.
```
I figured if I just call `generate_statusline` twice (`true|false`) this will generate all required `highlight` groups so that the `highlight` command isn't called as part of the initial `vim.o.statusline` generation:
```lua …
```

fix for issue#23, feline makes splash screen disappear

---

lua/feline/init.lua
lua/feline/providers/lsp.lua

Before
```lua
...
require("feline.generator"): 3.6887ms (0.192100 -> 3.880800)
require("feline.defaults"): 0.0656ms (0.337900 -> 0.403500)
require("feline.defaults"): 0.0003ms (0.404700 -> 0.405000)
require("feline.providers"): 3.4574ms (0.405400 -> 3.862800)
require("feline.providers.vi_mode"): 0.0802ms (0.572700 -> 0.652900)
require("feline.defaults"): 0.0005ms (0.650500 -> 0.651000)
require("feline.providers.cursor"): 0.0683ms (0.653200 -> 0.721500)
require("feline.providers.file"): 0.1017ms (0.722100 -> 0.823800)
require("feline.providers.lsp"): 2.952ms (0.824300 -> 3.776300)
require("vim.uri"): 0.0639ms (0.902300 -> 0.966200)
require("bit"): 0.0003ms (0.965000 -> 0.965300)
require("vim.lsp"): 2.8082ms (0.966500 -> 3.774700)
require("vim.F"): 0.0251ms (1.439900 -> 1.465000) …
```

Stop `vim.lsp` from loading eagerly

---

README.md

The original code used `#%d+` to match the hex value, which wouldn't work for hex values with letters A-F, so i changed the pattern to `#[0-9A-Fa-f]+` instead.

Fix thin line for inactive statusline example

---

README.md
lua/feline/generator.lua
lua/feline/providers/file.lua
lua/feline/providers/git.lua
lua/feline/providers/lsp.lua

Closes #28
I took a stab at trying add `icon` as field for any component. Due to the fact that the builtin providers have fallback icons, I needed to introduce an optional return value for all builtin providers. This was probably the easiest solution that wouldn't require refactoring how providers work in feline. 
Additionally, `icon` can accept a table. The fields accepted are exactly the same as the fields accepted for the separators.
I also refactored  some of the LSP providers. `lsp_client_names` no longer has an icon after every attached client so it can benefit from the new fields added to `icon`. `diagnostic_`* functions now check if LSP is attached or if no diagnostics are available.
I tested all the builtin providers and so far everything works as expected. I will add docs once …

Add icon field to all components

---

lua/feline/providers/file.lua

The color of icons are maintained by plugin nvim-web-devicons.
I don't know if it should be the default. If an extra option is fine, I will add it later.

Make icon colorful for `file_info` provider

---

lua/feline/providers/git.lua

`\uf9c9` (the default icon of `git_diff_changed` provider) in nerd font is larger (2 spaces) than it is expected (1 space). It can be confirmed in kitty, konsole, and hyper.
This makes it looks weird in terminal.
I don't know why, but I removed a trailing space to make it look good.
Before:
After:

Remove extra space in `git_diff_changed` provider

---

lua/feline/providers/file.lua

I've found a new bug introduced in #38 . The file icon's background color automatically turns blacker with Normal when my feed background color is light.
before version:
fixed version:

Fix highlight background for `file_info`

---

lua/feline/providers/cursor.lua
lua/feline/providers/file.lua
lua/feline/providers/vi_mode.lua

https://github.com/famiu/feline.nvim/pull/40#issuecomment-909975582 inspired me to replace as many `vim.fn` calls with either `vim.api` functions or vim statusline items (see http://vimdoc.sourceforge.net/htmldoc/options.html#'statusline').

perf(providers): reduce `vim.fn` calls

---

README.md
lua/feline/presets/default.lua
lua/feline/providers/file.lua

https://github.com/famiu/feline.nvim/issues/37#issuecomment-909849267 wasn't a fan of colored icons by default, so perhaps this should be behind a setting. I am wondering if it should be the default behaviour though, and instead allow the user to disable the colored icons if they want to.

feat(file_info): add `colored_icon` option

---

lua/feline/init.lua

Current master doesn't work when you run `require('feline').setup()` because of the depreciation warnings. I have also moved `require('feline.presets')` to stop it from eagerly loading when a custom config is being used. 
I have tested all the three variations of setup (https://github.com/famiu/feline.nvim/tree/master#1-using-default-statusline) and tested my own config.

fix: ensure config keys exist

---

lua/feline/init.lua

If you have a custom `force_inactive` table defined, it will instead disable the statusline for the respective files/buffers.

fix: make disable inherit correct table

---

lua/feline/generator.lua

Closes: #23
`parent_bg` can be `nil`, which resulted in the the splash screen bug.
cc: @ibhagwan @famiu

fix: ensure that parent_bg has a value

---

.github/workflows/docs.yaml
README.md

I saw a comment on the reddit post you made about the lack of a vimdoc file. I have written docs for people in the past but this README is massive (that's a good thing), so I took inspiration from shadmansaleh's lualine and tried out https://github.com/kdheepak/panvimdoc. 
The github workflow is mostly borrowed from https://github.com/shadmansaleh/lualine.nvim/blob/master/.github/workflows/docs.yml. 
- The workflow runs whenever there is a change in the README pushed to any branch, this should probably be limited to the develop branch, however, I wanted your input first. 
- I had to add an empty an empty doc file in this PR so the workflow can submit a PR. 
- Also, I changed the formatting slightly in the README to accomodate for the generated vimdoc.
- Not sure if the `HOW TO INSTALL` …

feat: add auto vimdoc generation workflow

---

README.md
lua/feline/generator.lua

~~Closes #23~~
Not sure if this is the most elegant solution, however, since it might cause some slowdowns for string values of `hl`

Fixes related to component highlight generation

---

README.md
lua/feline/generator.lua
lua/feline/providers/cursor.lua
lua/feline/providers/file.lua
lua/feline/providers/git.lua
lua/feline/providers/lsp.lua
lua/feline/providers/vi_mode.lua

BREAKING CHANGE: The arguments for provider functions have been changed.
Prerequisite for component truncation (#96). This seems to be working fine. Would still like a review from @ram02z

refactor: separate provider options from component values

---

lua/feline/providers/file.lua

No need to extract the foreground color manually from highlight due to https://github.com/kyazdani42/nvim-web-devicons/pull/82

chore: use `get_icon_color`

---

USAGE.md
lua/feline/generator.lua

Closes #96 
Seems to be working fine. Though I'd like @ram02z to review the code (and try to make it simpler if possible). I'd also like it to be well-tested before merge.

feat: add smart component truncation

---

USAGE.md
lua/feline/defaults.lua
lua/feline/generator.lua
lua/feline/init.lua
lua/feline/providers/cursor.lua
lua/feline/providers/file.lua
lua/feline/providers/git.lua
lua/feline/providers/lsp.lua
lua/feline/providers/vi_mode.lua

BREAKING CHANGE: The statusline providers no longer take a `winid` argument. Now you need to use `vim.api.nvim_get_current_win()` to get the statusline window and `vim.api.nvim_get_current_buf()` for the statusline buffer. For the actual current window / buffer, you need to use `vim.g.actual_curwin` and `vim.g.actual_curbuf`, respectively.  As a result of this change, the `update_triggers` option has also been removed.
Still need to add docs before I can merge this

refactor: evaluate providers in context of statusline window

---

USAGE.md
lua/feline/generator.lua
lua/feline/statusline_ffi.lua

Now fully supports VIm statusline expressions. Thanks to @shadmansaleh for assisting with the FFI code required for that. This should work perfectly fine. The only issue is that it causes a 53% performance downgrade, which is a pretty big issue. The downgrade is not really noticable to me but not sure about others. Not a fan of it using FFI to access Neovim's internals either, mostly because I don't have much knowledge about Neovim internals so it'd be a pain to troubleshoot a problem if the source of the problem is the FFI code.

refactor: re-add smart component truncation

---

README.md

Since Feline.nvim has been transferred to the `feline-nvim` organization, the old repo link is now replaced by the new repo link in the README

docs(README): update links to feline repo

---

lua/feline/presets/default.lua
lua/feline/presets/noicon.lua
lua/feline/providers/file.lua

Hello, 
TLDR: Every buildin provider except the `file_info` provider returns a string without trailing whitespace. In order to be consistent, the `file_info` provider should adapt to this behaviour. The missing whitespace can easily be added by the user by using separators.
Long version: Consider the following example
```lua
table.insert(components.active[1], {
provider = 'file_info'
})
table.insert(components.active[1], {
provider = 'git_branch',
-- Only show the git branch, when the current file is inside the git repo
enabled = function ()
local path = vim.fn.expand('%:p')
local cwd = vim.fn.getcwd()
if path:find(cwd) ~= nil then return true end
end,
})
table.insert(components.active[1], {
provider = 'file_size',
left_sep = ' ',
})
```
When the `git_branch` section is enabled, all three …

"file_info" provider should not return a trailing whitespace

---

lua/feline/providers/lsp.lua

Currently `diagnostic_warnings` and `diagnostic_info` don't work on 0.6 due to the severity name.
Since most of the functions now are `diagnostic` related, I wonder if changing the filename from `lsp.lua` will be more suitable.
Requires neovim 0.6, so probably hold off on merging or we could patch the two functions that don't work on neovim 0.6.

refactor: use vim.diagnostic for lsp provider

---

lua/feline/providers/git.lua

When autochdir is disabled and user switches to a non-git file, the branch icon remains.
Closes #194

fix: only check buffer local gitsigns info

---

.github/release.yml

With this we can automatically generate the release notes https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

chore: add release.yml

---

lua/feline/providers/file.lua

To have more consistency with Neovim's built-in statusline configuration.

fix: show "[No Name]" instead of "unnamed" for unnamed buffers

---

USAGE.md
lua/feline/generator.lua
lua/feline/init.lua

Ref: #170
Adds two utility functions, `require('feline').is_component_truncated` and `require('feline').is_component_hidden` to check if a component has been truncated or hidden.

feat: add utility functions to check component truncation

---

lua/feline/init.lua

Previously, Feline configuration couldn't be reloaded due to the custom providers from the previous configuration being cached, causing an error if a provider with the same name was in the new configuration as well. This commit fixes that by unloading the feline providers Lua module before loading it, to prevent its values from being cached.
Closes #229

fix: allow reloading feline configuration

---

USAGE.md
lua/feline/generator.lua
lua/feline/init.lua
lua/feline/utils.lua

Providers can now be updated by autocmd and function triggers in order to prevent re-running a function everytime the statusline is generated.
Closes #227

feat: allow updating providers through triggers

---

lua/feline/providers/file.lua

When opening an empty buffer and using the file_info provider with
opts.type = 'relative', the filename ends up becoming CWD. The solution
is to check that the filename is not empty, set it to '[No Name]' and
then skip all transformations.

fix(providers/file_info): don't transform the empty filename

---

lua/feline/providers/file.lua

This should solve #249
With the following files/buffers:
- python and rust files (because extension != filetype)
- `CMakeLists.txt` (previously a wrong icon was displayed)
- `.bashrc` (previously a wrong icon was displayed)
- buffers not linked to a file (NvimTree, Outline, Trouble...)
- common files (where extension = filetype)
It seems to work fine for these use-cases and for the most common ones, but we'd need some time make sure these changes works well with edge-cases too

fix: use nvim-web-devicons correctly in file providers

---

USAGE.md

Minor touch-ups to `USAGE.md`.
* added `lua` syntax highlighting to code snippet blocks
* removed a trailing whitespace

docs: USAGE minor formatting clean up

---

lua/feline/providers/file.lua

`jdt.ls` generates filenames with `%` in them e.g. 
```
jdt://contents/java.base/java.lang/StringBuilder.class?=jacoco/%5C/usr%5C/lib%5C/jvm%5C/java-17-openjdk-17.0.3.0.7-1.fc36.x86_64%5C/lib%5C/jrt-fs.jar%60java.base=/maven.pomderived=/true=/=/ja
vadoc_location=/https:%5C/%5C/docs.oracle.com%5C/en%5C/java%5C/javase%5C/17%5C/docs%5C/api%5C/=/%3Cjava.lang(StringBuilder.class
```
The `file_info` component reverse searches for the first occurrence of `/`, which in this case will contain `%3Cjava.lang(StringBuilder.class`. Unfortunately, `%` is a special character in the statusline (as you probably know), which causes feline to crash (in my case it's the winbar that's crashing).
Something to consider: you might want extract this escaping logic into a user-facing utils function. For instance, …

fix: escape special statusline chars in filename component

---

USAGE.md
lua/feline/providers/file.lua

`get_path_separator` function is originally from the plenary path module.
https://github.com/nvim-lua/plenary.nvim/blob/4b66054e75356ac0b909bbfee9c682e703f535c2/lua/plenary/path.lua#L21
Closes #301

feat: add path_sep option to file_info provider

---

.github/workflows/pr_check.yml

This way any non-breaking fixes to stylua-action will automatically be
used as v1 points to the latest version.
Also upgrade checkout to version 3.

ci: bump stylua-action to version to v1

---

lua/feline/generator.lua

When provider is a table with update key, the provider cache table gets printed.
```lua
provider = {
name = "file_type",
update = {
"FileType",
},
}
```
Remove the print function call along with the if statement.
https://github.com/feline-nvim/feline.nvim/blob/5d6a054c476f2c2e3de72022d8f59764e53946ee/lua/feline/generator.lua#L296-L298

fix: remove unwanted print function call

---

USAGE.md
lua/feline/providers/cursor.lua
lua/feline/providers/init.lua

Apparently checking for nil will keep the indicator active, just like the hlsearch one

feat: Added `macro` provider

---

README.md
lua/feline/providers/cursor.lua

I'm still getting the same error in #328 because in #329 empty check is done using `result == {}`, but in lua `{} == {}` is false. Using `next(result) == nil` check (taken from https://stackoverflow.com/a/1252776) works.

fix(providers): search_count with empty results
